import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ModeToggle from "@/components/mode-toggle";
import { SidebarProvider, SidebarTrigger  }  from "@/components/ui/sidebar";
import  { AppSidebar }  from "@/components/app-sidebar";
import { IconGitBranch } from "@tabler/icons-react"

import { Button } from "@/components/ui/button"



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export function ButtonWithIcon() {
  return (
    <Button variant="outline" size="sm">
      <IconGitBranch /> New Branch
    </Button>
  )
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <div className="flex h-screen"> {/* use h-screen instead of h-full */}
              {/* Sidebar */}
              <AppSidebar />

              {/* Main content area */}
              <div className="flex flex-col flex-1 h-full overflow-hidden">
                {/* Top bar */}
                <div className="flex justify-end p-4 border-b shrink-0">
                  <ModeToggle />
                </div>

                {/* Scrollable content */}
                <main className="flex-1 min-h-0 overflow-y-auto p-4"> {/* add min-h-0 */}
                  <SidebarTrigger />
                  {children}
                </main>
              </div>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}









